### ISSUE TITLE
What's the real name of this tool?[Doc]: 

### ISSUE THREAD

**Issue by JackPaul** [oceanbase/sql-lifecycle-management#20]
### Check Before Asking

- [X] Please check the issue list and confirm this issue is encountered for the first time.

### Description

Why the logo and title of home page is SQL Less?

### Documentation Links

......

### Are you willing to submit a pull request?

- [X] Yes I am willing to submit a pull request.

**Comment by luliwjc** [comment]
Hi, Jack, our open source name is sql-lifecycle-management
