### ISSUE TITLE
[Bug]: order_list error for functioncall

### ISSUE THREAD

**Issue by luliwjc** [oceanbase/sql-lifecycle-management#23]
### Check Before Asking

- [X] Please check the issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
v0.1.0
```

### Fast Reproduce Steps

select department_id ,  count ( * ),max(gid)  from staff_department_assignments group by department_id order by count ( * )  desc,max(gid)

### Actual Behavior

order_list has no gid column

**Comment by Ifffff** [comment]
Thank you for your feedback, but this sql will use `count(*)` to sort first, and the subsequent `gid` will not be used. Even if it is `order by max(gid)`, since the `gid` after group by is unordered, the `gid` column will not be used for sorting

**Comment by luliwjc** [comment]
Yes,you are right, gid must be in projection_column_list?

**Comment by Ifffff** [comment]
Yes，in this sql , projection_column_list = ['department_id', 'count(*)', 'gid']

**Comment by luliwjc** [comment]
ok
