### ISSUE TITLE
[Bug]: set_list NullLiteral error

### ISSUE THREAD

**Issue by luliwjc** [oceanbase/sql-lifecycle-management#34]
### Check Before Asking

- [X] Please check the issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
v0.1.0
```

### Fast Reproduce Steps

UPDATE table SET consumer_server_ip = NULL WHERE biz_date = '2021-08-13 00:00:00' AND consumer_server_ip = 'xxxx'

### Actual Behavior

NullLiteral object has no attribute 'value'

**Comment by Ifffff** [comment]
no recurrence
close
