### ISSUE TITLE
[Bug]: length of columns in some meta table need to be longer

### ISSUE THREAD

**Issue by TyphoonTai** [oceanbase/sql-lifecycle-management#35]
### Check Before Asking

- [X] Please check the issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Fast Reproduce Steps

`host_ip` varchar(32) DEFAULT NULL COMMENT 'DB服务器地址，pull授权必填'

In some cases, we may use dns instead of ip, so this column's length may be too short. Please change this init.sql and make it more suitable.

### Actual Behavior

`host_ip` varchar(32) DEFAULT NULL COMMENT 'DB服务器地址，pull授权必填'

In some cases, we may use dns instead of ip, so this column's length may be too short. Please change this init.sql and make it more suitable.

**Comment by luliwjc** [comment]
ok, we will extend the host_ip field length definition.
You can modify the field length of your database first to avoid this problem.
Thanks for feedback!
