### ISSUE TITLE
[Bug]: select boolean expression parse error

### ISSUE THREAD

**Issue by luliwjc** [oceanbase/sql-lifecycle-management#40]
SELECT T1.list_followers, T2.user_subscriber = 1 FROM lists AS T1 INNER JOIN lists_users AS T2 ON T1.user_id = T2.user_id AND T2.list_id = T2.list_id WHERE T2.user_id = 4208563 ORDER BY T1.list_followers DESC LIMIT 1
 
![image](https://github.com/oceanbase/sql-lifecycle-management/assets/27209261/e5ea8610-3e85-437f-8229-000ab67be650)

**Comment by Ifffff** [comment]
Thanks for feedback

tips:
also consider 
T2.user_subscriber between 1 and 2
T2.user_subscriber like 'a%'
etc.

the impact of filter_column_list should be considered
