### ISSUE TITLE
[Doc]: Docs about architecture is needed

### ISSUE THREAD

**Issue by archerny** [oceanbase/sql-lifecycle-management#51]
Through the [official website(Chinese)](https://www.oceanbase.com/docs/community), you can find all the documents about OceanBase.

**Description**
New beginners like me will be at loss in face to the bulk of code. I think this project needs some docs that introduces its code, how to contribute, architecture and so on.

**Documentation Links**
No.

**Additional context**
No.

**Comment by Ifffff** [comment]
Thanks for feedback.
We will continue to update some articles introducing architecture, core technology, etc. Thank you for your attention.
