### ISSUE TITLE
[Doc]: there is no init.sql file in init directory

### ISSUE THREAD

**Issue by wakaka2019** [oceanbase/sql-lifecycle-management#7]
### Check Before Asking

- [X] Please check the issue list and confirm this issue is encountered for the first time.

### Description

![image](https://github.com/oceanbase/sql-lifecycle-management/assets/65145640/7e22262a-5baf-4b45-b8fc-68671e137f4c)
![image](https://github.com/oceanbase/sql-lifecycle-management/assets/65145640/4d42a304-7d99-4ea0-8639-7ac9c470593e)

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a pull request.

**Comment by Ifffff** [comment]
Thanks, forgot it
