### ISSUE TITLE
[Bug]: lead function is not support

### ISSUE THREAD

**Issue by Ifffff** [oceanbase/sql-lifecycle-management#97]
**Describe the bug**
```sql
select 
    distinct t.num as ConsecutiveNums 
from
(
    select
        num, 
        lag(num, 1, null) over(order by id) as lag_num, 
        lead(num, 1, null) over(order by id) as lead_num
    from Logs
) t
where t.num = t.lag_num and t.num = t.lead_num
```
an error happened when parser this sql.
```
E           SyntaxError: The current version does not support this SQL 30 (() 
E                    lag(num, 1, null) over(order by id) as lag_num, 
```

**Comment by qidi1** [comment]
It causes by the window function is not supported.
- [x] support window function in parser.
   - [x] ROW_NUMBER
   - [x] RANK
   - [x] DENSE_RANK
   - [x] CUME_DIST
   - [x] PERCENT_RANK
   - [x] NTILE
   - [x] LEAD
   - [x] LAG
   - [x] FIRST_VALUE
   - [x] LAST_VALUE
   - [x] NTH_VALUE
 - [ ] support window function in format.
   - [ ] ROW_NUMBER
   - [ ] RANK
   - [ ] DENSE_RANK
   - [ ] CUME_DIST
   - [ ] PERCENT_RANK
   - [ ] NTILE
   - [ ] LEAD
   - [ ] LAG
   - [ ] FIRST_VALUE
   - [ ] LAST_VALUE
   - [ ] NTH_VALUE
 - [ ] support window function in optimize.
   - [ ] ROW_NUMBER
   - [ ] RANK
   - [ ] DENSE_RANK
   - [ ] CUME_DIST
   - [ ] PERCENT_RANK
   - [ ] NTILE
   - [ ] LEAD
   - [ ] LAG
   - [ ] FIRST_VALUE
   - [ ] LAST_VALUE
   - [ ] NTH_VALUE
